version: 1
formatters:
  simple:
    format:
      "%(levelname)s %(asctime)s [%(name)s:%(filename)s:%(funcName)s:%(lineno)d]\n%(message)s\n"
  color:
    format: "%(log_color)s%(levelname)-8s%(reset)s%(asctime)s %(bg_blue)s[%(name)s]%(reset)s %(message)s"
    datefmt: "%m-%d %H:%M:%S"
    class: colorlog.ColoredFormatter
handlers:
  console:
    class: colorlog.StreamHandler
    formatter: color
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: simple
    filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
root:
  handlers:
    - console
    - file

disable_existing_loggers: false
